---
- name: Populate service facts
  service_facts:

- name: Install the Grafana Agent
  shell: >
    ARCH=amd64
    GCLOUD_STACK_ID="{{GCLOUD_STACK_ID}}"
    GCLOUD_API_KEY="{{GCLOUD_API_KEY}}"
    GCLOUD_API_URL="https://integrations-api-us-central.grafana.net"
    /bin/sh -c "$(curl -fsSL https://raw.githubusercontent.com/grafana/agent/release/production/grafanacloud-install.sh)"
  when: "'grafana-agent.service' not in services"

- name: Set hostname
  replace:
    path: /etc/grafana-agent.yaml
    regexp: "instance: hostname"
    replace: "instance: {{ inventory_hostname }}"
  notify:
    - restart grafana-agent
