---
- name: Set logging
  ufw:
    logging: "on"

- name: Allow SSH in UFW
  ufw:
    rule: allow
    port: ssh
    proto: tcp

- name: Allow http
  ufw:
    rule: allow
    port: 80
    proto: tcp

- name: Allow https
  ufw:
    rule: allow
    port: 443
    proto: tcp

- name: Deny incoming internet traffic
  ufw:
    rule: deny
    interface_in: "{{ ansible_default_ipv4.interface }}"

- name: Set firewall default policy
  ufw:
    state: enabled
    policy: allow
