---
- name: Install HAProxy
  apt:
    name: haproxy
    state: latest
    update_cache: true

- name: Copy haproxy.cfg
  template:
    src: haproxy.cfg
    dest: /etc/haproxy/haproxy.cfg

- name: Restart haproxy
  service: name=haproxy state=restarted

- name: Allow http
  ufw:
    rule: allow
    port: "80"
    proto: tcp

- name: Allow http
  ufw:
    rule: allow
    port: "443"
    proto: tcp
