apiVersion: v1
kind: ConfigMap
metadata:
  name: hobby-cluster-loki
  namespace: {{ .Release.Namespace }}
  labels:
    app: loki
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    grafana_datasource: "1"
data:
  loki-stack-datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Loki
      type: loki
      access: proxy
      url: {{ .Values.lokiURL }}
      version: 1
