controller:
  kind: DaemonSet
  config:
    use-proxy-protocol: "true"
    enable-opentracing: "true"
    jaeger-collector-host: grafana-agent-traces.default.svc.cluster.local
    opentracing-operation-name: "$request_method $host $uri"
  service:
    nodePorts:
      http: 30080
      https: 30443
