---
- name: Deploy k3s node
  hosts: node_0

  vars_prompt:
    - name: tailscale_auth_key
      prompt: Enter the Tailscale Auth key

    - name: GCLOUD_STACK_ID
      prompt: GCLOUD_STACK_ID

    - name: GCLOUD_API_KEY
      prompt: GCLOUD_API_KEY

  gather_facts: false

  pre_tasks:
    - name: Wait for ssh to come up
      wait_for_connection:
        timeout: 30
    - name: Gather facts
      gather_facts:

  roles:
    - role: grafana_agent
    - role: ufw
    - role: tailscale
    - role: k3s
    - role: ssh_hardening
