---
- name: Deploy k3s node
  hosts: all

  vars_prompt:
    - name: tailscale_auth_key
      prompt: Enter the Tailscale Auth key

  gather_facts: false

  pre_tasks:
    - name: Wait for ssh to come up
      wait_for_connection:
        timeout: 30
    - name: Gather facts
      gather_facts:

  roles:
    - role: ufw
    - role: tailscale
    - role: k3s
    - role: ssh_hardening
