---
- hosts: all
  become: yes
  tasks:
    - name: Install snap
      apt:
        name: snapd
        state: latest
        update_cache: true

    - name: Install microk8s
      snap:
        name: microk8s
        classic: yes

    - name: Get microk8s status
      shell: microk8s status --wait-ready --format short
      changed_when: false
      register: microk8s_status

    - name: Enable cilium
      command: microk8s enable cilium
      ignore_errors: yes
      when: '"cilium: enabled" not in microk8s_status.stdout_lines'
      register: cilium_enabled

    - name: Enable ingress
      command: microk8s enable ingress
      when: '"ingress: enabled" not in microk8s_status.stdout_lines'

    - name: Enable CoreDNS
      command: microk8s enable dns
      when: '"dns: enabled" not in microk8s_status.stdout_lines'

    - name: Reboot to clean up mess in iptables rules
      reboot:
      when: cilium_enabled is changed

    - name: Allow microk8s API server
      ufw:
        rule: allow
        interface: tailscale0
        direction: in
        port: "16443"
        proto: tcp

    - name: Create kubectl config
      changed_when: true
      shell: >
        microk8s config -l
        | sed 's/127.0.0.1/{{ ansible_tailscale0.ipv4.address }}/g'
        > $HOME/.kube/config

    - name: Fetch kubeconfig
      fetch:
        src: ~/.kube/config
        dest: ~/.kube/microk8s-kubeconfig
        flat: yes
