---
- hosts: all
  become: yes
  tasks:
    - name: Get microk8s status
      shell: k3s kubectl get nodes
      ignore_errors: true
      changed_when: microk8s_status.rc != 0
      register: microk8s_status

    - name: Install k3s
      shell: curl -sfL https://get.k3s.io | sh -
      when: microk8s_status is changed

    - name: Allow microk8s API server
      ufw:
        rule: allow
        interface: tailscale0
        direction: in
        port: "6443"
        proto: tcp

    - name: Create kubectl config
      changed_when: true
      shell: >
        cat /etc/rancher/k3s/k3s.yaml
        | sed 's/127.0.0.1/{{ ansible_tailscale0.ipv4.address }}/g'
        > $HOME/.kube/config

    - name: Fetch kubeconfig
      fetch:
        src: ~/.kube/config
        dest: ~/.kube/microk8s-kubeconfig
        flat: yes
