---
- hosts: all
  become: yes
  vars_prompt:
    - name: tailscale_auth_key
      prompt: Enter the Tailscale Auth key
  tasks:
    - name: Add Tailscale's package signing key
      apt_key:
        url: https://pkgs.tailscale.com/stable/ubuntu/focal.gpg
        state: present

    - name: Add Tailscale's repository
      apt_repository:
        repo: deb https://pkgs.tailscale.com/stable/ubuntu focal main
        state: present

    - name: Install Tailscale
      apt:
        name: tailscale
        state: latest
        update_cache: true

    - name: Check if Tailscale is connected
      command: tailscale status
      changed_when: false
      register: tailscale_status
      failed_when:
        - tailscale_status.rc != 0
        - "'Logged out.' not in tailscale_status.stdout"

    - name: Bring Tailscale Up
      command: tailscale up --advertise-exit-node --authkey={{ tailscale_auth_key }}
      no_log: true
      register: tailscale_start
      when: "'Logged out.' in tailscale_status.stdout"

    - sysctl:
        name: net.ipv4.ip_forward
        value: "1"
        sysctl_set: yes
        state: present
        reload: yes

    - sysctl:
        name: net.ipv6.conf.all.forwarding
        value: "1"
        sysctl_set: yes
        state: present
        reload: yes
