---
- name: Deploy k3s node
  hosts: vpn

  gather_facts: false

  pre_tasks:
    - name: Wait for ssh to come up
      wait_for_connection:
        timeout: 30
    - name: Gather facts
      gather_facts:

  roles:
    - role: ipsec_vpn
    - role: ssh_hardening
